--- #YAML:1.0
name:               MooseX-YAML
version:            0.04
abstract:           ~
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    MooseX::Blessed::Reconstruct:  0.03
    namespace::clean:     0
    Sub::Exporter:        0.982
    Test::use::ok:        0
    YAML:                 0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
